image: docker:dind

stages:
- build
- release
- deploy

variables:
  IMAGE_PATH: vfricou/unison-server
  CONTAINER_BUILD_IMAGE: ${CI_DOCKER_REGISTRY_HOST}/${IMAGE_PATH}:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: ${CI_DOCKER_REGISTRY_HOST}/${IMAGE_PATH}:latest
  CONTAINER_RELEASE_IMAGE_TAG: ${CI_DOCKER_REGISTRY_HOST}/${IMAGE_PATH}:$CI_COMMIT_TAG

build:docker:
  stage: build
  script:
    - docker build -t ${CONTAINER_BUILD_IMAGE} .

release-image:latest:
  stage: release
  script:
    - docker login -u ${CI_DOCKER_REGISTRY_USER} -p ${CI_DOCKER_REGISTRY_PASS} ${CI_DOCKER_REGISTRY_HOST}
    - docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

release-image:tags:
  stage: release
  script:
    - docker login -u ${CI_DOCKER_REGISTRY_USER} -p ${CI_DOCKER_REGISTRY_PASS} ${CI_DOCKER_REGISTRY_HOST}
    - docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_RELEASE_IMAGE_TAG
    - docker push $CONTAINER_RELEASE_IMAGE_TAG
  only:
    - tags